[package]
name = "very_simple_2d"
version = "0.1.0"
authors = ["Ken <kenakioreed@gmail.com>"]
build = "build.rs"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
axgeom = "1.2"

[dev-dependencies]
glutin = {git="https://github.com/rust-windowing/glutin.git"}

[build-dependencies]
gl_generator = "0.13.0"



