[package]
name = "very_simple_2d"
version = "0.1.0"
authors = ["Ken Reed <kenakioreed@gmail.com>"]
repository = "https://github.com/tiby312/very_simple_2d"
readme = "README.md"
edition = "2018"


[workspace]
members = [ "very_simple_2d_core"]

[dependencies]
axgeom = "1.4"
very_simple_2d_core = {path="./very_simple_2d_core"}
glutin = "0.22.0-alpha5"
